create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  title text not null,
  completed boolean not null default false,
  created_at timestamptz not null default now()
);
